#!/bin/bash

CC="gcc -Wall -o"

$CC keygen keygen.c 
$CC otp_dec otp_dec.c otp.c otp_core.c
$CC otp_dec_d otp_dec_d.c otp_d.c otp_core.c
$CC otp_enc otp_enc.c otp.c otp_core.c
$CC otp_enc_d otp_enc_d.c otp_d.c otp_core.c
